scrape_twitter:
  description: >
    Search Twitter for {topic}. The current timestamp is {timestamp}. Scroll through the page, extract the number of requested tweets and format them as JSON with fields: id, content, user, timestamp, likes, retweets, has_photos.
  expected_output: >
    JSON string with tweets array containing id, content, user, timestamp, likes, retweets, has_photos.
  agent: twitter_agent
  output_file: "output/tweets.json"
search_google:
  description: >
    Use serperdevtool to search Google for {topic} context. Prepare the searchresults as a list of websites with the title, url, snippet and date.
  expected_output: >
    Markdown list of websites with the title, url, snippet and date.
  agent: google_agent
  output_file: "output/google_search.md"
read_articles:
  description: >
    Read 1-2 articles and summarize them in 150 words each.
  expected_output: >
    Markdown article with titles and ~150 summary for each article read.
  agent: article_reader
  context: [search_google]
  output_file: "output/article_summary.md"
write_article:
  description: >
    Combine Twitter and Google findings to write ~150 word article about {topic}.
    Article should be engaging and interesting.
    Backup your story with facts, figures and sources.
  expected_output: >
    Markdown article with title and ~150 word content.
  agent: article_writer
  output_file: "output/article.md"
  context: [scrape_twitter, read_articles]
