web_search_task:
  description: >
    Perform targeted Google news searches for {topic} using Serper Dev Tool.
    Focus on finding the most recent and relevant news articles (last 24 hours) from credible sources.
    Select the top 2-3 articles based on:
    - Relevance to the topic
    - Source credibility (prefer established news outlets)
    - Publication date (prioritize most recent)
    - Content quality indicators (length, depth, citations)
  expected_output: >
    A structured JSON object containing:
    - selected_articles: Array of 2-3 articles with metadata:
      * title
      * url
      * source
      * date
      * snippet
      * imageUrl
    - search_parameters: The original search parameters used
      * query
      * date_range
      * language
      * country
  agent: web_research_agent
  output_file: web_search_results.json
  constraints:
    - max_results: 3
    - min_word_count: 500
    - allowed_domains: [nytimes.com, bbc.com, reuters.com, apnews.com, standardmedia.co.ke, citizen.digital, foxnews.com]  # Example of trusted sources

read_and_summarize_task:
  description: >
    Analyze and summarize content from the 2-3 articles selected in the web_search_task.
    Extract key information and create a comprehensive news summary including:
    - Main points and arguments
    - Important facts and figures
    - Relevant quotes or statements
    - Source credibility assessment
    - Potential biases or limitations
  expected_output: >
    A structured news report in Markdown format containing:
    1. Overview of the topic
    2. Summary of findings from each article (2-3 paragraphs per article)
    3. Key insights and conclusions
    4. Source references with:
       * Title
       * URL
       * Publication date
       * Source name
    The report should be 300-500 words, written in journalistic style.
  agent: web_research_agent
  context: [web_search_task]
  output_file: news_summary.md
  constraints:
    - summary_length: 300-500 words
    - include_source_analysis: true
    - include_key_quotes: true
