twitter_scraper_task:
  description: >
    Scrape tweets from twitter about a given topic.
  expected_output: >
    A JSON string that can be parsed for downstream tasks.
  agents: 
    - political_news_reporter
    - business_news_reporter
    - sports_news_reporter

google_news_search_task:
  description: >
    Search for news articles on Google News about a given topic.
  expected_output: >
    A JSON string that can be parsed for downstream tasks.
  agents: 
    - political_news_reporter
    - business_news_reporter
    - sports_news_reporter

writing_task:
  description: >
    Write a news article about a given topic.
  expected_output: >
    A news article in markdown format.
  agents: 
    - political_news_reporter
    - business_news_reporter
    - sports_news_reporter