search_news:
  description: "search for news from past 24 hours using news search tool. topic: {q1}"
  expected_output: "GoogleNewsResults object with searchParameters and news articles"
  agent: "researcher"
  context: []

search_images:
  description: "search for images from past 24 hours using image search tool"
  expected_output: "GoogleImageResults object with searchParameters and image details"
  agent: "researcher"
  context: ["search_news"]

search_tweets:
  description: "search for tweets using twitter scraper tool, topic:{twitter_query}."
  expected_output: "JSON array of tweets with content, author, and engagement metrics"
  agent: "researcher"
  context: ["search_news", "search_images"]

read_websites:
  description: "read few websites using read website content tool"
  expected_output: "JSON content of scraped websites with text and metadata"
  agent: "analyst"
  context: ["search_news"]

take_screenshots:
  description: "take 1 screenshot of a top tweet using take tweet screenshot tool. only select a tweet without an image"
  expected_output: "JSON with local paths to the screenshots"
  agent: "analyst"
  context: ["search_tweets"]

analyse_images:
  description: "analyse images using image analysis tool. select one of them as a fetured image and 2-3 as in-content images including the twitter screenshot."
  expected_output: "JSON analysis of image content, subjects, and context. the choices you made and why the image fits the context"
  agent: "analyst"
  context: ["search_images", "take_screenshots"]

download_images:
  description: "download images from url and resize them to blog size. download the featured image with bool featured_image=true"
  expected_output: "JSON with local paths to downloaded and resized images and their descriptions"
  agent: "analyst"
  context: ["analyse_images"]

upload_images:
  description: "upload images to blob storage and get a URI that will be embedded as markdown"
  expected_output: "JSON with image URIs and their descripttions"
  agent: "analyst"
  context: ["download_images"]

write_article:
  description: "write an engaging news article that will be published on my blog. "
  expected_output: "DraftArticle object with title, slug, content, and metadata"
  agent: "writer"
  context: ["search_news", "read_websites", "upload_images"]

review_article:
  description: "review the article you have written for completeness"
  expected_output: "Revised article content"
  agent: "writer"
  context: ["write_article"]

format_input:
  description: "review article fields to conform to model requirements"
  expected_output: "FinalArticle object with all required fields populated"
  agent: "writer"
  context: ["review_article"]

publish_article:
  description: "publish article to neo4j database"
  expected_output: "Confirmation message with art.slug published to neo4j database"
  agent: "writer"
  context: ["format_input"]