search_news:
  description: >
    Use the Google News Search tool to perform comprehensive news searches about the provided query(ies), if any:
    {google_query_1}, 
    {google_query_2}, 
    {google_query_3}, 
    country(ies): {country} 
    
  expected_output: >
    A JSON structure containing news search results including:
    - searchParameters: object containing q (query(ies)), type, and engine
    - news: array of news items, each containing:
      - title: article title
      - link: article URL
      - snippet: brief summary of article content
      - date: publication date
      - source: publication source
      - position: ranking position in results
  agent: researcher
  output_file: z_output/search_news.json

scrape_tweets:
  description: >
    Use the Twitter scraper tool to scrape {max_tweets} tweets about {twitter_query},
    Set is_hashtag={is_hashtag}
    You dont have to do any analysis, just scrape the tweets

    Return A structured JSON collection of scraped tweets including:
    - tweets: array of tweet objects containing:
      - tweet id
      - content
      - user
      - timestamp
      - likes
      - retweets
      - has_photos
    - trend: the search query used
    - count: total number of tweets collected
  
  expected_output: >
    A structured JSON collection of scraped tweets in the following format:
    {
      "tweets": [
        {
          "tweet_id": "1234567890",
          "content": "This is a tweet",
          "user": "user123",
          "timestamp": "2021-01-01 12:00:00",
          "likes": 10,
          "retweets": 5,
          "has_photos": true
        }
      ]
      "trend": "twitter_query",
      "count": 10
    }
  agent: researcher
  output_file: z_output/scrape_tweets.json

search_images:
  description: >
    Use the Image Search Tool to find relevant, high-quality images related to the context that could be used to 
    illustrate the news article.
    search query: {google_query_1}
    country(ies): {country} 
    
  expected_output: >
    A JSON structure containing image search results including:
    - searchParameters: object containing q (query), type, engine, and num
    - images: array of image objects, each containing:
      - title: image title or description
      - imageUrl: URL of the full-size image
      - imageWidth: width dimension of the full image
      - imageHeight: height dimension of the full image
      - thumbnailUrl: URL of the thumbnail version
      - thumbnailWidth: width dimension of the thumbnail
      - thumbnailHeight: height dimension of the thumbnail
      - source: source website or attribution information
  agent: researcher
  output_file: z_output/search_images.json

read_website:
  description: >
    Use the Scrape Website tool to extract raw html or text content from news websites identified in the search_news task. 
    End Goal: {my_thoughts}
    Use the end goal to determine the most relevant articles to read.
    
    Your task is to:
    1. Visit each high-priority news URL identified in the search_news results based on the end goal
    2. Extract the full article HTML or text, headline, and metadata
    3. Skip any webpages that output error messages e.g 403, 404, require cookies, or have strong bot restrictions.
    4. Return the raw html or text content of each scraped website.
  
  expected_output: >
    Raw HTML or text content of the scraped website. The output will be the full page content as a string, 
    which could include:
    {
      "website_url": "https://www.example.com",
      "content": "Raw HTML or text content of the website"
    }
  agent: writer
  context: [search_news]
  output_file: z_output/read_website.json

write:
  description: >
    Based on the research gathered from news sources and social media, 
    {my_thoughts}. 
    Synthesize the information into a cohesive narrative
    that presents the story accurately and completely.
    
    Your task is to:
    1. Create a compelling headline that accurately represents the content
    2. Write a concise summary that captures the essence of the story
    3. Develop a structured article with a clear introduction, body, and conclusion
    4. Incorporate verified facts, quotes, dates,and data from the research
    5. Present multiple perspectives when the topic involves different viewpoints
    6. Maintain a neutral, objective tone adhering to journalistic standards
    7. Identify and extract relevant entities (people, organizations, locations) mentioned
    8. Generate appropriate keywords and tags for the article
    9. Create a URL-friendly slug for the article
    
    Ensure the article follows the inverted pyramid style where appropriate, 
    with the most important information appearing first.
  expected_output: >
    A complete draft article in the format specified by the DraftArticle model, including:
    - Compelling headline and URL-friendly slug
    - Concise summary of the key points
    - Well-structured article body with proper paragraphing
    - Properly attributed quotes and sources
    - List of relevant keywords for SEO and categorization
    - Named entities extracted from the article
    - Content that meets journalistic standards for accuracy, fairness, and completeness
    - Mention dates, time and financial constraints if necessary
    
  agent: writer
  context: [read_website, scrape_tweets]
  output_file: z_output/write.json

select_image:
  description: >
    Use the Image Analysis Tool and image title and description to select the most appropriate image to accompany the article from the collection gathered during the image_search task. 
    Choose an image that best represents the article's content and will engage readers.
    
    Your task is to:
    1. Review 1-2 images(exclude thumbnails) collected during the image search
    2. Evaluate each image for relevance to the specific article angle
    3. Consider image quality, composition, and impact
    4. Ensure the image is recent and accurately represents the current situation
    5. Verify that proper attribution is available for the selected image
    6. Choose both a main feature image and a thumbnail version
    7. Provide proper citation and source information
    
    Select an image that adds informational value and enhances understanding 
    of the story, not just decorative value.
  expected_output: >
    A selection decision including:
    - URL of the selected main image and its thumbnail
    - Make sure the image URLs do not contain query parameters like quality or width.
    - Remove any parameters from image URLs (everything after the ? character). For example, change "image.jpg?width=800&quality=80" to just "image.jpg".
    - Title/caption for the image
    - Source attribution information
    - Brief explanation of why this image best represents the article
    - Any relevant context about what the image depicts

  agent: writer
  context: [search_images]
  output_file: z_output/select_image.json

format:
  description: >
    Review and finalize the article for publication, ensuring it meets all technical 
    and editorial requirements. Transform the draft article into the final format 
    ready for publishing to the Neo4j database.
    
    Your task is to:
    1. Review the article for accuracy, clarity, and completeness
    2. Ensure all required fields are present and properly formatted
    3. Verify category and subcategory assignments are appropriate
    4. Confirm author attribution based on the category/subcategory
    5. Check that the selected image is properly integrated
    6. Finalize metadata including keywords, entities, and publication status
    7. Format the article according to the FinalArticle model specifications
    8. Perform a final check for any factual errors or missing information
    
    This is the last quality check before publication, so be thorough in ensuring 
    all requirements are met.
  expected_output: >
    A publication-ready article formatted according to the FinalArticle model, including:
    - All required fields properly populated
    - Correct category, subcategory, and author assignments got from {category}
    - Properly integrated images with correct URLs and attribution
    - Complete metadata (keywords, entities, etc.)
    - Properly formatted content that meets style guidelines
    - Confirmation that the article meets all quality standards
    - story: {story}, publisher: 'joelmbaka.site'
  agent: editor
  context: [write, select_image]
  output_file: z_output/format.json

publish:
  description: >
    Publish the finalized article to the Neo4j database using the Neo4j Article Tool. 
    This is the final step that makes the article available to readers.
    
    Your task is to:
    1. Verify that the article meets all publication requirements
    2. Prepare the article data in the format required by the Neo4j database
    3. Submit the article to the database using the Neo4j Article Tool
    4. Confirm successful publication and storage
    5. Document any issues encountered during the publishing process
    
    Ensure that the article is properly stored with all metadata intact and 
    that it's ready for retrieval and display to readers.
  expected_output: >
    return f"Successfully stored article with title: '{created_node[0]['art.title']}', slug: '{created_node[0]['art.slug']}', published at: {created_node[0]['art.publishedAt']}"
  agent: editor
  context: [format]
  output_file: z_output/publish.json